### ISSUE TITLE
Cannot build with haskell-src-exts-1.16.0

### ISSUE THREAD

**Issue by arpunk** [chrisdone/structured-haskell-mode#83]
Hi,

I get the following while trying to install structured-haskell-mode-1.0.3:

```
Configuring structured-haskell-mode-1.0.3...
Building structured-haskell-mode-1.0.3...
Preprocessing executable 'structured-haskell-mode' for
structured-haskell-mode-1.0.3...
[1 of 1] Compiling Main             ( src/Main.hs, dist/build/structured-haskell-mode/structured-haskell-mode-tmp/Main.o )

src/Main.hs:143:21:
    Not in scope: data constructor ‘IHead’
    Perhaps you meant ‘DHead’ (imported from Language.Haskell.Exts.Annotated)

src/Main.hs:144:21:
    Not in scope: data constructor ‘IHead’
    Perhaps you meant ‘DHead’ (imported from Language.Haskell.Exts.Annotated)
```

I'm using cabal-install-1.20.0.3, GHC 7.8.3 and haskell-platform 2014.2.0.0
